sfdc:
  username: "![4F599VJR302IqELkRXwH5lo3oiyJGzoELfbCb3N9vJM=]"
  password: "![6QULwRkE9aWZH29xmYVN1A==]"
  token: "![vfPm57GEr+OtZBd+6jSKtx3WWIv8Ivzcn5jFwRfzoXQ=]"

ssl:
   password: "![KBYEEZ7MyV6CGVr6biyDMQ==]"
   
       